### ISSUE TITLE
Winforms example

### ISSUE THREAD

**Issue by rigler86** [jliliamen/WordPressLicenseManagerNETClient#2]
can you please provide an example of a project with winform for using this? I'm new to coding and need help in understanding its implementation for activating, deactivating, and checking license on application load.

**Comment by AmenJlili** [comment]
@rigler86 ill get to this in a couple of days. Meanwhile, what are you trying to do with the lib if you don't mind me asking?

**Comment by rigler86** [comment]
Well, im hoping to use it to control licensing with the WordPress license manager plugin. I want to load a form for activation, enable deactivation via a button on the program when activated. I also want to display a status in the footer of the program showing active after the check is done for the license. I want the program to check for license on each load and if not active show a message to renew or purchase license, after the message box is closed the program closes.

**Comment by AmenJlili** [comment]
@rigler86 : Sorry im extremely busy now. If you are a professional code for hire, please send me an email @ amen@bluebyte.biz let's talk via Zoom https://calendly.com/bluebyte

**Comment by AmenJlili** [comment]
Anyone want to jump and create a example. Your PR is my guest?
