### ISSUE TITLE
  restRequest.Method should be RestSharp.Method.GET;

### ISSUE THREAD

**Issue by xavave** [jliliamen/WordPressLicenseManagerNETClient#4]
Hello,
thanks a lot for your implementation
in order to work with a custom dotnet program , your restrequestmethod needs to be a GET , not a POST in licensemanager.cs 
method :  public ILicenseResponse PerformAction(Consts.Action action, License license)
line 72 :   restRequest.Method = RestSharp.Method.POST; -->   restRequest.Method = RestSharp.Method.GET;

as documented here:
https://www.tipsandtricks-hq.com/license-manager-product-communication-7985

I've tried with POST but wordpress just sends back the homepage so the request fails, whereas with a get method, your licensemanager client works as expected

**Comment by AmenJlili** [comment]
Will investigate this... Thanks

**Comment by AmenJlili** [comment]
You are more than welcome to do a pull request btw

**Comment by xavave** [comment]
thank you
pull request is made :https://github.com/jliliamen/WordPressLicenseManagerNETClient/pull/5

**Comment by AmenJlili** [comment]
I have recompiled a new version and pushed it into nuget 
https://www.nuget.org/packages/WPLMNETClient/1.0.2

I'm closing to close this issue. You can create new issues for other stuff! Merci!
