### ISSUE TITLE
PerformActionAsync issue when a SOLIDWORKS PDM add-in is loaded into the administration tool

### ISSUE THREAD

**Issue by Alex-Egorchatov** [jliliamen/WordPressLicenseManagerNETClient#8]
During testing, this function returns only such values as Result and Message. However, if the add-in is running in the Administration Tool, then this function returns null.

**Comment by AmenJlili** [comment]
Whenever making any web API calls either in SOLIDWORKS or PDM. Always include this line in OnCmd or the ConnectToSW ( for sw add-ins)

```      ServicePointManager.SecurityProtocol |=SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12; ```


Let me know if it works.

**Comment by AmenJlili** [comment]
Namespace is ``` using System.Net; ```

**Comment by Alex-Egorchatov** [comment]
Thank you, now it works.
